# Supabase local development config

[api]
enabled = true
port = 54321
schemas = ["public"]
max_rows = 1000
[db]
port = 54322
[studio]
enabled = true
port = 54323
[functions]
  enabled = true
  [functions.node_runtime]
    enabled = false
[auth]
enabled = true
site_url = "http://localhost:5173"

